export const labels = {
  AADHAAR: "Aadhaar Card No",
  ACC_YEAR: "Academic Year",
  ACTIVE: "Active",
  ADDMISSION_NO_PREFIX: "Addmission # Prefix",
  ADDRESS: "Correspondence Address",
  ADDRESS_1: "Address 1",
  ADDRESS_2: "Address 2",
  ADDRESS_INFORMATION: "Address Information",
  ADD_LOGO: "Upload Logo",
  AFFILIATION: "Affiliation",
  ALIAS: "Alias",
  AS_PER_AADHAAR: "(As per aadhaar card)",
  ATTEMPTS_GIVEN:"Attempts given, if any",
  BLOOD_GROUP: "Blood Group",
  BLOOD_GROUP_ABN: "AB-",
  BLOOD_GROUP_ABP: "AB+",
  BLOOD_GROUP_AN: "A-",
  BLOOD_GROUP_AP: "A+",
  BLOOD_GROUP_BN: "B-",
  BLOOD_GROUP_BP: "B+",
  BLOOD_GROUP_ON: "O-",
  BLOOD_GROUP_OP: "O+",
  BRANCH_APPLIED_FOR: "Branch Applied For",
  BRANCH_NAME: "Org Name",
  BUTTON_ADD: "Add",
  BUTTON_BACK: "Back",
  BUTTON_BACK_TO_LOGIN: "Back to login",
  BUTTON_CANCEL: "Cancel",
  BUTTON_CHECK: "Check",
  BUTTON_DELETE: "Delete",
  BUTTON_DELETE_GRID: " ",
  BUTTON_DOWNLOAD: "Download",
  BUTTON_EDIT: "Edit",
  BUTTON_FORGOT_PASSWORD: "Forgot password",
  BUTTON_LOGIN: "Login",
  BUTTON_NEW: "New",
  BUTTON_REGISTRATION: "Register",
  BUTTON_RESET: "Reset",
  BUTTON_SAVE: "Save",
  BUTTON_SAVE_CLOSE: "Save & Close",
  BUTTON_SAVE_CONTINUE: "Save & Continue",
  BUTTON_SEND: "Send",
  BUTTON_UPDATE: "Update",
  BUTTON_UPLOAD: "Upload",
  CATEGORY: "Select Category",
  CITY: "City",
  CLASS: "Class",
  CLASS_APPLIED_FOR: "Class Applied For",
  CLASS_NAME: "Class Name",
  COMMENTS: "Comments",
  COMMUNICATION_CONTACT_NUMBER: "Communication Number",
  COMMUNICATION_EMAIL: "Communication Email",
  CONTACT: "Contact Number",
  CONTACT_PREFRENCE:"Would you be interested to receive a call or message from us",
  COUNSELING_SATISFACTION:"Are you satisfied with the counseling",
  COUNTRY: "Country",
  COURSE: "Course",
  DATE: "Date",
  DD_MM_YYYY: "(dd/mm/yyyy)",
  DEPARTMENT: "Department",
  DESIGNATION: "Designation",
  DISCOUNT: "Discount",
  DOB: "Date of Birth",
  EMAIL: "Email Id",
  EMAIL_VERIFIED: "Email Verified?",
  EMP_CODE: "Emp Code",
  ESTB_YEAR: "Est Year",
  EXAM_NAME: "Exam Name",
  FATHER: "Father",
  FATHER_INFORMATION: "Father Information",
  FIRST_NAME: "First Name",
  FOUNDER_NAME: "Founder's Name",
  GENDER: "Gender",
  GENDER_FEMALE: "Female",
  GENDER_MALE: "Male",
  GRADE_NAME: "Grade Name",
  GRADE_PERCENTAGE_FROM: "Percentage From",
  GRADE_PERCENTAGE_TO: "Percentage To",
  GRADE_POINT: "Grade Point",
  GUARDIAN: "Guardian",
  INSTUT_TYPE: "Instutition Type",
  LABEL: "Label",
  LANDLINE: "Landline",
  LAST_NAME: "Last Name",
  LINK: "Link",
  LOADING: "Loading...",
  MARITAL_STATUS: "Marital Status",
  MARRIED: "Married",
  MEDICAL_CONDITION: "Medical Condition (if any)",
  MIDDLE_NAME: "Middle Name",
  MOTHER: "Mother",
  MOTHER_INFORMATION: "Mother Information",
  NAME: "Candidate Name (as in 10Th Marks Card)",
  NATIONALITY: "Nationality",
  OCCUPATION: "Occupation",
  OFFICE_ADDRESS: "Office address",
  OFFICE_NUMBER: "Office No",
  OPTIONAL_SUBJECT: "Optional Subject",
  ORGANIZATION: "Organization",
  ORG_NAME: "Org Name",
  PAGE_NOT_FOUND: "404 Page not found",
  PAN_CARD: "Pan Card No",
  PASSWORD: "Password",
  PHOTO: "Upload Photo",
  PHOTO_SIZE: "(Max upload fize size 2 MB)",
  PIN_CODE: "Pin Code",
  PLACE_HOLDERS: {
      DOB: "dd/mm/yyyy",
      EMAIL: "email@address.com",
      PASSWORD: "Password"
  },
  PLEASE_SELECT: "Please select",
  PRESENT_CLASS_NAME: "Present Class",
  PRESENT_SCHOOL_NAME: "Present School Name",
  PRIMARY_MOBILE: "Whatsapp Contact No",
  QUALIFICATION: "Qualification",
  REFERAL_SOURCE:"How did you get to know about us",
  REG_NO: "Registration No",
  RELATIONSHIP: "Relationship",
  REMARKS:"Remarks",
  REQUIRED_ASTRIX: ' *',
  RESCHEDULED_DATE:'Rescheduled Date',
  ROLE: "Role",
  ROLE_ADMIN: "Admin",
  ROLE_SUPER_ADMIN: "SuperAdmin",
  ROLE_TEACHER: "Teacher",
  SALARY: "Salary",
  SECONDARY_MOBILE: "Alternate Mobile",
  SECTION: "Section",
  SECTION_APPLIED_FOR: "Section Applied For",
  SELECT_CLASS: "Select Class",
  SELECT_DATE: "Select Date",
  SELECT_SECTION: "Select Section",
  SELECT_SUBJECT: "Select Subject",
  SELECT_SUBJECTS: "Select Subjects",
  SELECT_TEACHER: "Select Teacher",
  SELECT_THEME: "Select Theme",
  SELECT_TIME: "Select Time",
  SELECT_TIMETABLE: "Select Timetable",
  SHOW_PASSWORD: "Show Password",
  SOCIAL_FB: "Facebook",
  SOCIAL_INSTA: "Instagram",
  SOCIAL_TWITTER: "Twitter",
  SOCIAL_YOUTUBE: "YouTube",
  STAFF_INFORMATION: "Staff Information",
  STATE: "State",
  STATUS: "Status",
  STUDENT_INFORMATION: "Student Information",
  SUBJECT: "Subject",
  SUBJECT_CODE: "Subject Code",
  SUBJECT_NAME: "Subject Name",
  SUBJECT_TYPE: "Subject Type",
  TEACHER: "Teacher",
  TIME: "Time",
  TIME_FROM: "Select Time From",
  TIME_TO: "Select Time To",
  TITLES: {
      FORGOT_PASSWORD: "F O R G O T - P A S S W O R D",
      LOGIN: "L O G I N",
      REGISTRATION: "R E G S T R A T I O N"
  },
  UNAUTHORIZED_ACCESS: "Access Denied",
  UNKNOWN: "Unknown",
  UNMARRIED: "Unmarried",
  UPLOAD_IMAGE: "Upload Image",
  URL: "URL",
  USER_ID: "User Id",
  VALUE: "Value"
};
